Description: >
    This template deploys an EC2 cluster to the provided VPC and subnets 
    using an Auto Scaling Group

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    InstanceType:
        Description: EC2 instance type
        Type: String
        Default: t2.medium
        AllowedValues: [t2.micro, t2.small, t2.medium, t2.large, m3.medium, m3.large,
        m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
        c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
        r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
        ConstraintDescription: Please choose a valid instance type.

    ClusterSize:
        Description: How many hosts do you want to initially deploy?
        Type: Number
        Default: 3

    VPC:
        Description: Choose which VPC this cluster should be deployed to
        Type: AWS::EC2::VPC::Id

    KeyName:
        Default: ''
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        Type: 'AWS::EC2::KeyPair::KeyName'

    Subnets:
        Description: Choose which subnets this cluster should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    LoadBalancer:
        Description: The VPC that the ECS cluster is deployed to
        Type: String

    LoadBalancerSecurityGroup:
        Description: Select the Load Balancer Security Group to use for the cluster hosts
        Type: AWS::EC2::SecurityGroup::Id

    Path: 
        Description: The path to register with the Application Load Balancer
        Type: String
        Default: /

    FQDN:
        Type: String
        Description: Fully qualified URL for using app.  DNS of FQDN must be pointed to CNAME of ALB.

    CertificateArn:
        Type: String
        Description: SSL cert for AWS ALB HTTPS listener

    MinClusterSize:
        Description: Minimum hosts to deploy
        Type: Number
        Default: 1

    MaxClusterSize:
        Description: Maximum hosts to deploy
        Type: Number
        Default: 5

    SSHFrom:
        Description: Lockdown SSH access to the bastion host (default can be accessed from anywhere)
        Type: String
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.

    HostVolumeSize:
        Description: Size in GB of additional non-root volume
        Type: String
        Default: '128'
        AllowedValues:
        - '8'
        - '16'
        - '32'
        - '64'
        - '128'
        - '256'
        - '512'
        - '1024'
        - '2048'
        - '4096'

    BlockVolumeSize:
        Description: Size in GB of additional non-root volume
        Type: String
        Default: '256'
        AllowedValues:
        - '8'
        - '16'
        - '32'
        - '64'
        - '128'
        - '256'
        - '512'
        - '1024'
        - '2048'
        - '4096'

Mappings:
    #We use default AWS Amazon AMI and install docker.
    #Rancher OS Amis: https://github.com/rancher/os/blob/master/README.md
    #Amazon AMI: https://aws.amazon.com/amazon-linux-ami/

    AWSRegionToAMI:
        us-east-1:
            AMI: ami-428aa838
        # us-east-2:
        #     AMI: ami-f63b1193
        # us-west-1:
        #     AMI: ami-c4b3bca4
        # us-west-2:
        #     AMI: ami-6e1a9e16
        # eu-west-1:
        #     AMI: ami-a7f2acc1
        # eu-west-2:
        #     AMI: ami-3fb6bc5b
        # eu-central-1:
        #     AMI: ami-ec2be583
        # ap-northeast-1:
        #     AMI: ami-c393d6a4
        # ap-southeast-1:
        #     AMI: ami-a88530cb
        # ap-southeast-2:
        #     AMI: ami-8af8ffe9
        # ca-central-1:
        #     AMI: ami-ead5688e

Resources:

    EC2AutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties: 
            VPCZoneIdentifier: !Ref Subnets
            LaunchConfigurationName: !Ref EC2LaunchConfiguration
            MinSize: !Ref MinClusterSize
            MaxSize: !Ref MaxClusterSize
            DesiredCapacity: !Ref ClusterSize
            Tags:
                - Key: Name
                  Value: !Join 
                    - '-'
                    - - !Ref 'EnvironmentName'
                      - 'EC2-Instance'
                  PropagateAtLaunch: true
        CreationPolicy:
            ResourceSignal: 
                Timeout: PT15M
        UpdatePolicy:
            AutoScalingRollingUpdate:
                MinInstancesInService: 1
                MaxBatchSize: 1
                PauseTime: PT15M
                SuspendProcesses:
                  - HealthCheck
                  - ReplaceUnhealthy
                  - AZRebalance
                  - AlarmNotification
                  - ScheduledActions
                WaitOnResourceSignals: true

    # This security group defines who/where is allowed to access the hosts directly.
    # By default we're just allowing access from the load balancer.  If you want to SSH 
    # into the hosts, or expose non-load balanced services you can open their ports here.
    EC2HostSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            VpcId: !Ref VPC
            GroupDescription: Access to the hosts and the tasks/containers that run on them
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  CidrIp: "0.0.0.0/0"
                - IpProtocol: udp
                  FromPort: 0
                  ToPort: 65535
                  CidrIp: "0.0.0.0/0"
            Tags: 
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Hosts
        
    EC2LaunchConfiguration:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            ImageId:  !FindInMap [AWSRegionToAMI, !Ref "AWS::Region", AMI]
            InstanceType: !Ref InstanceType
            SecurityGroups: 
                - !Ref EC2HostSecurityGroup
            IamInstanceProfile: !Ref EC2InstanceProfile
            KeyName: !Ref KeyName
            AssociatePublicIpAddress: true
            BlockDeviceMappings:
            - DeviceName: /dev/xvda
              Ebs:
                VolumeSize: !Ref HostVolumeSize
                DeleteOnTermination: 'true'
            # - DeviceName: /dev/xvdb
            #   Ebs:
            #     VolumeSize: !Ref BlockVolumeSize
            #     DeleteOnTermination: 'true'
            UserData: 
                "Fn::Base64": !Sub |
                    #!/bin/bash
                    yum install -y aws-cfn-bootstrap
                    yum update -y
                    mount --make-shared /
                    /opt/aws/bin/cfn-init -v -c standard --region ${AWS::Region} --stack ${AWS::StackName} --resource EC2LaunchConfiguration
                    /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource EC2AutoScalingGroup

        Metadata:
            AWS::CloudFormation::Init:
                configSets:
                    standard:
                    - "standard"
                standard:
                    files:
                        "/etc/cfn/cfn-hup.conf":
                            mode: 000400
                            owner: root
                            group: root
                            content: !Sub |
                                [main]
                                stack=${AWS::StackId}
                                region=${AWS::Region}
                        
                        "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
                            content: !Sub |
                                [cfn-auto-reloader-hook]
                                triggers=post.update
                                path=Resources.EC2LaunchConfiguration.Metadata.AWS::CloudFormation::Init
                                action=/opt/aws/bin/cfn-init -v -c standard --region ${AWS::Region} --stack ${AWS::StackName} --resource EC2LaunchConfiguration
                    services: 
                        sysvinit:
                            cfn-hup: 
                                enabled: true
                                ensureRunning: true
                                files: 
                                    - /etc/cfn/cfn-hup.conf
                                    - /etc/cfn/hooks.d/cfn-auto-reloader.conf
                    commands:
                        1_install_docker:
                            command: !Sub sudo yum -y install docker
                        2_change_cluster_storage_driver:
                            command: !Sub echo 'DOCKER_STORAGE_OPTIONS="--storage-driver overlay2"' > /etc/sysconfig/docker-storage
                        3_space_sshd_config:
                            command: !Sub echo '' >> /etc/ssh/sshd_config
                        4_edit_sshd_config:
                            command: !Sub echo 'AllowTcpForwarding yes' >> /etc/ssh/sshd_config
                        5_edit_sshd_config2:
                            command: !Sub echo 'PermitTunnel yes' >> /etc/ssh/sshd_config
                        6_add_user_to_docker:
                            command: !Sub usermod -a -G docker ec2-user
                        7_update_docker_service:
                            command: !Sub echo "MountFlags=shared" >> /usr/lib/systemd/system/docker.service
                        8_start_docker:
                            command: !Sub service docker start
                        9_restart_sshd:
                            command: !Sub service sshd restart

    EC2Role:
        Type: AWS::IAM::Role
        Properties: 
            Path: /
            RoleName: !Sub ${EnvironmentName}-EC2Role-${AWS::Region}
            AssumeRolePolicyDocument: |
                {
                    "Statement": [{
                        "Action": "sts:AssumeRole",
                        "Effect": "Allow",
                        "Principal": { 
                            "Service": "ec2.amazonaws.com" 
                        }
                    }]
                }
            Policies: 
                - PolicyName: ec2-service
                  PolicyDocument: |
                    {
                        "Statement": [{
                            "Effect": "Allow",
                            "Action": [
                                "autoscaling:Describe*",
                                "logs:CreateLogStream",
                                "logs:PutLogEvents",
                                "ecr:BatchCheckLayerAvailability",
                                "ecr:BatchGetImage",
                                "ecr:GetDownloadUrlForLayer",
                                "ecr:GetAuthorizationToken",
                                "ec2:Describe*",
                                "ec2:AttachVolume",
                                "ec2:DetachVolume",
                                "ec2:CreateTags",
                                "ec2:CreateVolume",
                                "ec2:DeleteTags",
                                "ec2:DeleteVolume",
                                "ec2:DescribeTags",
                                "ec2:DescribeVolumeAttribute",
                                "ec2:DescribeVolumesModifications",
                                "ec2:DescribeVolumeStatus",
                                "ec2:DescribeVolumes",
                                "ec2:DescribeInstances",
                                "elasticloadbalancing:*",
                                "ec2:*"
                            ],
                            "Resource": "*"
                        }]
                    }

    EC2InstanceProfile: 
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles: 
                - !Ref EC2Role

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 14  

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId: !Ref VPC
            Port: 443
            Protocol: HTTPS
            Matcher: 
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 60
            HealthCheckPath: /healthz
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 30
            TargetGroupAttributes:
                - Key: deregistration_delay.timeout_seconds
                  Value: '700'
                - Key: stickiness.type
                  Value: lb_cookie
                - Key: stickiness.enabled
                  Value: 'false'
                - Key: stickiness.lb_cookie.duration_seconds
                  Value: '1860'
            Name: !Join 
                - '-'
                - - !Ref 'EnvironmentName'
                  - RancherTG

    Listener:
        Type: 'AWS::ElasticLoadBalancingV2::Listener'
        Properties:
            Certificates: 
                - CertificateArn: !Ref CertificateArn
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref TargetGroup
            LoadBalancerArn: !Ref LoadBalancer
            Port: '443'
            Protocol: HTTPS
    
    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 1
            Conditions:
                - Field: path-pattern
                  Values: 
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward


Outputs:

    AutoScalingGroup:
        Description: A reference to the auto scaling group
        Value: !Ref EC2AutoScalingGroup

    AutoScalingRole:
        Description: A reference to the auto scaling role
        Value: !GetAtt EC2Role.Arn

    EC2HostSecurityGroup:
        Description: A reference to the EC2HostSecurityGroup
        Value: !Ref EC2HostSecurityGroup
